  # description:
  
  in this description, it's assumed that user id is significant. 
  this test should create 2 snapshots, one for each user
  
  note: you may need to freeze this twice, because on first run 2 different calls
  are made for user 1, but only snapshot is stored. recalling first run is necesssary,
  because otherwise the system may get stuck on timeouts. this will cause the result to
  be different on second run, as in first run 2 calls are done, while on second run
  one snapshot is used twice.
  
! test raised exception 'HOST_NAME':                           | EOF
  Traceback (most recent call last):
    File "/home/arau/lumoa/src/booktest/booktest/testrun.py", line 105, in run_case
      rv = await maybe_async_call(case, [t], {})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/coroutines.py", line 6, in maybe_async_call
      return await func(*args2, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/env.py", line 128, in wrapper
      return await maybe_async_call(func, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/coroutines.py", line 6, in maybe_async_call
      return await func(*args2, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/env.py", line 190, in wrapper
      return await maybe_async_call(func, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/coroutines.py", line 6, in maybe_async_call
      return await func(*args2, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/requests.py", line 489, in wrapper
      return await maybe_async_call(func , args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/booktest/coroutines.py", line 8, in maybe_async_call
      return func(*args2, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
    File "/home/arau/lumoa/src/booktest/test/examples/snapshots_book.py", line 230, in test_requests_with_headers
      response = requests.post(os.environ["HOST_NAME"], json={
                               ~~~~~~~~~~^^^^^^^^^^^^^
    File "<frozen os>", line 679, in __getitem__
  KeyError: 'HOST_NAME'
  
